name: day25
version: 0.1.0.0
github: "heijp06/day25"
license: BSD3
author: "Peter van der Heijden"
maintainer: "peter@vanderheijden.name"
copyright: "Copyright 2020 Peter van der Heijden"
extra-source-files:
  - README.md
  - ChangeLog.md
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Home

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/heijp06/day25#readme>
dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src
  dependencies:
    - split
    - containers
    - utils
executables:
  day25:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - day25
      - hspec
      - Clipboard
      - split
      - containers
      - utils
      - intCode
      - mtl
tests:
  day25-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - day25
      - hspec
